### PR TITLE
Update to build 2047

### PR DESCRIPTION
**Pull request by ineol**

### CODE REVIEW

**Comment by ptomato** [comment]
Thanks!

**Comment by ptomato** [comment]
@ineol Are you interested in maintaining this app? You are much more active in updating it than I am.

**Comment by ineol** [comment]
@ptomato I would be very happy to!

**Comment by ptomato** [comment]
Thanks, see https://github.com/flathub/flathub/issues/2160

**Comment by ptomato** [comment]
Congratulations @ineol! :smile: :tada:

**Comment by ineol** [comment]
Thanks @ptomato !

**Pull request merged**
