### PR TITLE
Update to Freedesktop Sdk 21.08

### LINKED ISSUE #26: Update runtime to 21.08

### PR DESCRIPTION
**Pull request by jwillikers**
Fixes #26

### CODE REVIEW

**Comment by ptomato** [comment]
@jwillikers I built this and installed it but get a lot of visual corruption when I run it:
image
I assume you don't see the same thing?

cc @ineol

**Comment by jwillikers** [comment]
@ptomato On Fedora 35 I get issues like that when graphics acceleration is enabled. Is that the cause?

**Comment by ptomato** [comment]
Yes, it goes away if I disable HW acceleration. Must be some newer version of some component that's in both Freedesktop SDK 21.08 and Fedora 35.

**Comment by vulpes2** [comment]
@ptomato Would you mind testing this again? I just tried 21.08 on Fedora 36 and the graphics issue is no longer present with OpenGL enabled.

**Comment by ptomato** [comment]
Yes, whatever the problem was seems to have been fixed.

**Pull request merged**
