### PR TITLE
Update to build 2020

### PR DESCRIPTION
**Pull request by ineol**
Add permission to dri device because Sublime Merge is now able to use
hardware acceleration.

### CODE REVIEW

**Comment by ineol** [comment]
I just added the release notes.

**Comment by ptomato** [comment]
Thanks very much, and sorry about the delay on reviewing this. I let it go too long and the test build expired, so I'll try to trigger a new one:

bot, retest this please

**Comment by ptomato** [comment]
bot, build

**Comment by ptomato** [comment]
Thanks very much for the update. I'll merge this now.

**Comment by ineol** [comment]
Great, thanks!

**Pull request merged**
